/* NETLUXE — Catalogue domaine public (Internet Archive)
   Généré automatiquement. Tous les contenus sont dans le domaine public
   ou sous licence libre, diffusables légalement. */

var PUBLIC_DOMAIN_CATALOG = [
  {id:1000,title:'Popeye for President',type:'cartoon',year:1956,genre:'Animation',rat:4.4,dur:'8min',img:'https://archive.org/services/img/Popeye_forPresident',video:'https://archive.org/download/Popeye_forPresident/Popeye_forPresident_512kb.mp4',dir:'Seymour Kneitel',views:2206349,likes:176507,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'Popeye and Bluto are both running for president. They are tied with exactly the same number of votes, but Miss Olive Oyl has yet to cast her ballot. W'},
  {id:1001,title:'The Fast And The Furious',type:'film',year:1955,genre:'Classique',rat:4.1,dur:'1h30m',img:'https://archive.org/services/img/TheFastandtheFuriousJohnIreland1954goofyrip',video:'https://archive.org/download/TheFastandtheFuriousJohnIreland1954goofyrip/TheFastandtheFuriousJohnIreland1954goofyrip_512kb.mp4',dir:'John Ireland',views:1474471,likes:117957,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'http://imdb.com/title/tt0046969/ A man wrongly imprisoned for murder (John Ireland) breaks out of jail. He wants to clear his name, but with the polic'},
  {id:1002,title:'His Girl Friday',type:'film',year:1940,genre:'Classique',rat:4.0,dur:'91min',img:'https://archive.org/services/img/his_girl_friday',video:'https://archive.org/download/his_girl_friday/his_girl_friday_512kb.mp4',dir:'Howard Hawks',views:1300006,likes:104000,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'Hilarious romantic comedy starring Cary Grant and Rosalind Russell. Russell is rough and tumble reporter looking to get out of the news racket by marr'},
  {id:1003,title:'House on Haunted Hill',type:'film',year:1959,genre:'Classique',rat:3.9,dur:'74min',img:'https://archive.org/services/img/house_on_haunted_hill_ipod',video:'https://archive.org/download/house_on_haunted_hill_ipod/house_on_haunted_hill_512kb.mp4',dir:'William Castle',views:1030273,likes:82421,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'Frederick Loren has invited five strangers to a party of a lifetime. He is offering each of them $10,000 if they can stay the night in a house.'},
  {id:1004,title:'Jungle Book',type:'film',year:1942,genre:'Classique',rat:3.9,dur:'1h30m',img:'https://archive.org/services/img/JungleBook',video:'https://archive.org/download/JungleBook/Jungle_Book_512kb.mp4',dir:'Zoltan Korda',views:1011036,likes:80882,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'Teenaged Mowgli, who was raised by wolves, appears in a village in India and is adopted by Messua. Mowgli learns human language and some human ways qu'},
  {id:1005,title:'Patriotic Popeye',type:'cartoon',year:1957,genre:'Animation',rat:3.9,dur:'8min',img:'https://archive.org/services/img/popeye_patriotic_popeye',video:'https://archive.org/download/popeye_patriotic_popeye/popeye_patriotic_popeye_512kb.mp4',dir:'I. Sparber',views:1005926,likes:80474,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'Popeye\'s nephews want to play with fireworks on July 4th, but Popeye tries to dissuade them. They manage to light some off and get into trouble. Pope'},
  {id:1006,title:'Utopia',type:'film',year:1951,genre:'Classique',rat:3.9,dur:'141min',img:'https://archive.org/services/img/utopia',video:'https://archive.org/download/utopia/Utopia_512kb.mp4',dir:'Leo Joannon',views:928579,likes:74286,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'Utopia (also known as Atoll K and Robinson Crusoe Land) is last film Laurel and Hardy made together. It was filmed and produced in Europe.'},
  {id:1007,title:'Private Eye Popeye',type:'cartoon',year:1954,genre:'Animation',rat:3.9,dur:'8min',img:'https://archive.org/services/img/popeye_private_eye_popeye',video:'https://archive.org/download/popeye_private_eye_popeye/popeye_private_eye_popeye_512kb.mp4',dir:'Seymour Kneitel',views:898832,likes:71906,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'Olive Oyl is the femme fatale with a valuable, green, glowing jewel in need of protection. Popeye plays private eye and saves the day. Animation by To'},
  {id:1008,title:'Nazi Concentration Camps',type:'film',year:1945,genre:'Classique',rat:3.8,dur:'59min',img:'https://archive.org/services/img/nazi_concentration_camps',video:'https://archive.org/download/nazi_concentration_camps/nazi_concentration_camps_512kb.mp4',dir:'Domaine public',views:843444,likes:67475,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'**This film contains extremely graphic scenes of human suffering, please exercise caution when viewing.** Compilation footage of Nazi concentration ca'},
  {id:1009,title:'Abraham Lincoln',type:'film',year:1930,genre:'Classique',rat:3.8,dur:'84min',img:'https://archive.org/services/img/abraham_lincoln',video:'https://archive.org/download/abraham_lincoln/abraham_lincoln_512kb.mp4',dir:'D.W. Griffith',views:814988,likes:65199,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'A biography of the beloved United States president by D. W. Griffith. You can find more information regarding this film on its IMDb page .'},
  {id:1010,title:'The Child Molester',type:'film',year:1950,genre:'Science-Fiction',rat:3.8,dur:'20min',img:'https://archive.org/services/img/CHILD',video:'https://archive.org/download/CHILD/CHILD_512kb.mp4',dir:'N/A',views:764702,likes:61176,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'Produced by the Highway Safety Foundation in 1964, this shocking film deals with a subject quite taboo for its time. The short serves as a dramatized '},
  {id:1011,title:'Popeye: I Don\'t Scare',type:'cartoon',year:1956,genre:'Animation',rat:3.8,dur:'8min',img:'https://archive.org/services/img/popeye_i_dont_scare',video:'https://archive.org/download/popeye_i_dont_scare/popeye_i_dont_scare_512kb.mp4',dir:'I. Sparber',views:755184,likes:60414,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'Bluto bullies Popeye and attempts to sabotage Popeye\'s date with Olive. Animation by Tom Johnson and Frank Endres. Music by Winston Sharples. Produce'},
  {id:1012,title:'Suddenly',type:'film',year:1954,genre:'Classique',rat:3.8,dur:'75min',img:'https://archive.org/services/img/suddenly',video:'https://archive.org/download/suddenly/suddenly_512kb.mp4',dir:'Lewis Allen',views:733400,likes:58672,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'"Three gunmen, who have been hired to assassinate the President, hold a family hostage while waiting for their target. Interesting B film which focuse'},
  {id:1013,title:'Spree Lunch',type:'cartoon',year:1957,genre:'Animation',rat:3.8,dur:'8min',img:'https://archive.org/services/img/spree_lunch',video:'https://archive.org/download/spree_lunch/spree_lunch_512kb.mp4',dir:'Seymour Kneitel',views:725341,likes:58027,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'You can find more information regarding this film on its IMDb page .'},
  {id:1014,title:'The Stranger',type:'film',year:1946,genre:'Classique',rat:3.8,dur:'91min',img:'https://archive.org/services/img/TheStranger_0',video:'https://archive.org/download/TheStranger_0/The_Stranger_512kb.mp4',dir:'Orson Welles',views:656752,likes:52540,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'Set Connecticut after World War II, The Stranger is a cat and mouse game between Wilson (Edward G. Robinson), a member of the Allied War Crimes Commis'},
  {id:1015,title:'Tarzan\'s Revenge',type:'film',year:1938,genre:'Classique',rat:3.8,dur:'70min',img:'https://archive.org/services/img/tarzans_revenge',video:'https://archive.org/download/tarzans_revenge/tarzans_revenge_512kb.mp4',dir:'D. Ross Lederman',views:654452,likes:52356,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'You can find more information regarding this film on its IMDb page .'},
  {id:1016,title:'The Naked Witch',type:'film',year:1950,genre:'Science-Fiction',rat:3.8,dur:'59min',img:'https://archive.org/services/img/TheNakedWitch',video:'https://archive.org/download/TheNakedWitch/TheNakedWitch1964FullMovieFilmHorror.mp4',dir:'Domaine public',views:652033,likes:52162,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'One of Larry Buchanan\'s first films, so don\'t expect the polish and complex character interactions of his later work, like "Mars Needs Women" or "Zo'},
  {id:1017,title:'Popeye the Sailor: Nearlyweds',type:'cartoon',year:1956,genre:'Animation',rat:3.8,dur:'8min',img:'https://archive.org/services/img/Popeye_Nearlyweds',video:'https://archive.org/download/Popeye_Nearlyweds/Popeye_Nearlyweds_512kb.mp4',dir:'Seymour Kneitel',views:640832,likes:51266,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'Popeye and Olive have finally decided to get married. But that doesn\'t mean that Bluto is through trying to stop them. You can find more information '},
  {id:1018,title:'Mclintock',type:'film',year:1963,genre:'Classique',rat:3.8,dur:'1h30m',img:'https://archive.org/services/img/Mclintock.avi',video:'https://archive.org/download/Mclintock.avi/Mclintock_512kb.mp4',dir:'Andrew McLaglen, director',views:638752,likes:51100,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'This great comedy western stars John Wayne,Maureen O\'Hara,Patrick Wayne, Stefanie Powers,Chill Wills, and Strother Marten. There is a hilarious mudho'},
  {id:1019,title:'My Favorite Brunette',type:'film',year:1947,genre:'Classique',rat:3.8,dur:'86min',img:'https://archive.org/services/img/my_favorite_brunette',video:'https://archive.org/download/my_favorite_brunette/my_favorite_brunette_512kb.mp4',dir:'Elliott Nugent',views:636237,likes:50898,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'Bob Hope comedy with Dorothy Lamour. | You can find more information regarding this film on its IMDb page .'},
  {id:1020,title:'The House On Haunted Hill',type:'film',year:1959,genre:'Classique',rat:3.7,dur:'1h30m',img:'https://archive.org/services/img/House_On_Haunted_Hill.avi',video:'https://archive.org/download/House_On_Haunted_Hill.avi/The_House_on_Haunted_Hill_512kb.mp4',dir:'William Castle',views:603627,likes:48290,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'Vincent Price gives a stellar performance as the suavely malevolent host of a "haunted house party" who offers his guests $10,000 if they can survive '},
  {id:1021,title:'Betty Boop Cartoons',type:'cartoon',year:1950,genre:'Animation',rat:3.7,dur:'8min',img:'https://archive.org/services/img/BettyBoopCartoons',video:'https://archive.org/download/BettyBoopCartoons/Betty_Boop_More_Pep_1936_512kb.mp4',dir:'Domaine public',views:583543,likes:46683,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'This collection include 5 previously posted Betty Boop cartoons converted from DivX to QuickTime: Betty Boop: A Song a Day (1936), Betty Boop: Is My P'},
  {id:1022,title:'The Lost World',type:'film',year:1925,genre:'Classique',rat:3.7,dur:'68min',img:'https://archive.org/services/img/lost_world',video:'https://archive.org/download/lost_world/lost_world_512kb.mp4',dir:'Harry O. Hoyt',views:546134,likes:43690,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'The first film adaptation of Sir Arthur Conan Doyle\'s classic novel about a land where prehistoric creatures still roam.You can find more information'},
  {id:1023,title:'Grave of the Vampire',type:'film',year:1974,genre:'Science-Fiction',rat:3.7,dur:'89min',img:'https://archive.org/services/img/Grave_of_the_Vampire_movie',video:'https://archive.org/download/Grave_of_the_Vampire_movie/Grave-of-the-Vampire_512kb.mp4',dir:'John Hayes',views:536841,likes:42947,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'William Smith tracks down his father, a vampire who raped his mother. The IMDB entry is here . The mpeg2 file has nav-packets, so you can load it into'},
  {id:1024,title:'Killers From Space',type:'film',year:1954,genre:'Classique',rat:3.7,dur:'70min',img:'https://archive.org/services/img/Killers_from_space',video:'https://archive.org/download/Killers_from_space/Killers_from_space_512kb.mp4',dir:'W. Lee Wilder',views:534434,likes:42754,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'Attack by monsters from another planet! IMDB page'},
  {id:1025,title:'Elephants Dream',type:'cartoon',year:2006,genre:'Animation',rat:4.9,dur:'10min',img:'https://archive.org/services/img/ElephantsDream',video:'https://archive.org/download/ElephantsDream/ed_1024_512kb.mp4',dir:'Bassam Kurdali',views:3681295,likes:294503,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'From the official website : "Elephants Dream is the story of two strange characters exploring a capricious and seemingly infinite machine. The elder, '},
  {id:1026,title:'Charlie Chaplin Festival',type:'film',year:1938,genre:'Classique',rat:4.1,dur:'77min',img:'https://archive.org/services/img/charlie_chaplin_film_fest',video:'https://archive.org/download/charlie_chaplin_film_fest/charlie_chaplin_film_fest_512kb.mp4',dir:'Charles Chaplin',views:1502353,likes:120188,audio:['EN'],subs:[],org:false,source:'Internet Archive',license:'Domaine public',status:'live',desc:'Four Chaplin shorts from 1917: The Adventurer, The Cure, Easy Street and The Immigrant, presented with music and sound effects. You can find more info'},
];

/* Fusion avec le catalogue existant (originaux caribéens conservés) */
(function(){
  if(typeof CAT === 'undefined' || !Array.isArray(CAT)) return;
  var have = {};
  for(var i=0;i<CAT.length;i++) have[CAT[i].id] = true;
  var added = 0;
  for(var j=0;j<PUBLIC_DOMAIN_CATALOG.length;j++){
    var it = PUBLIC_DOMAIN_CATALOG[j];
    if(!have[it.id]){ CAT.push(it); added++; }
  }
  if(added && typeof console !== 'undefined') console.log('NETLUXE: '+added+' contenus domaine public ajoutés — total '+CAT.length);
  /* Re-render si l'app est déjà affichée */
  try {
    if(typeof renderHome === 'function') renderHome();
    else if(typeof init === 'function' && document.getElementById('app') &&
            getComputedStyle(document.getElementById('app')).display !== 'none') {
      if(typeof goHome === 'function') goHome();
    }
  } catch(e){}
})();